### ISSUE TITLE
Issue with Practice Tool

### ISSUE THREAD

**Issue by jeeerf** [veeenu/eldenring-practice-tool#127]
Hi veeenu,

I've been trying to get your Elden Ring Practice Tool to work on Crossover on my 2021 Macbook M1 Pro. I don't know if the fact that I'm using Crossover is the fundamental issue, but I seem to be getting an error according to the logs that I have attached. I'm not very familiar with code, so I would appreciate any help I can get with getting the tool to run! Thanks and please let me know if you need any more information.

[jdsd_er_practice_tool.log](https://github.com/user-attachments/files/16606132/jdsd_er_practice_tool.log)

**Comment by veeenu** [comment]
Hi,

I am not familiar with Crossover, but the error I see is coming from the initialization step of the hooking library, which makes me think OS X compatibility is going to be impossible.

This doesn't surprise me as M1 macs have a different processor architecture and OS X has a different way of protecting processes, which probably makes the hacks required to run the tool not really be able to be ported over in any meaningful way.

The error in question is `MH_ERROR_NOT_EXECUTABLE` which states that the rendering functions cannot be detoured because their memory space is not marked as executable. We know this is not true technically, but this is how Crossover exposes it and we can't do anything about it.

Sorry!
