### ISSUE TITLE
thread 'unnamed' panicked 

### ISSUE THREAD

**Issue by NevResTV** [veeenu/eldenring-practice-tool#32]
When I try to open the .exe it shows the window for the program start and immediately crahses after. Before the new update I did'nt had any problems with the tool. EAC is bypassed and tried with deactivated virus tool. when trying to find an error with the debug tool the game just won't open and crashes. GPU drivers are updated. OS is Windows 11
[practice_tool_log.zip](https://github.com/veeenu/eldenring-practice-tool/files/10299024/practice_tool_log.zip)

**Comment by veeenu** [comment]
Could you upload a log with only `log_level = "TRACE"` (and without `dxgi_debug = true`)?
Could you add more detailed information such as your [build number](https://support.microsoft.com/en-us/windows/which-version-of-windows-operating-system-am-i-running-628bec99-476a-2c13-5296-9dd081cdd808)?

I have theories as to why this might happen but I can't validate them because I can't reproduce the issue myself.

The one in your log looks like an "access denied" error which most often occurs either due to incorrect EAC bypass or antivirus software being still active. If you used the tool successfully before, EAC is probably correctly bypassed, and you mentioned having deactivated a virus tool.

Can you make _extra_ sure no process related to the antivirus is still active? Antivirus software tend to leave a lot of stuff running in the background. Windows Defender also counts as antivirus for that purpose.

(If you happen to solve your problem in this way, please add a comment confirming that so that I can rule out other causes.)

Merry Christmas!

**Comment by veeenu** [comment]
CC @etra0, looks like the same as the issue in `litcher`. I have a theory that there could be some race condition, and some nondescript resource is locked during the creation of the swap chain that results in the access being denied. But I have no idea how to test for that, nor how to reproduce that, nor how to work around that. I have been looking into pulling the address straight out of the DLL and thus avoid relying on any resources at all, but I am not sure that's even 100% possible or consistent.

**Comment by NevResTV** [comment]
[log2.zip](https://github.com/veeenu/eldenring-practice-tool/files/10301106/log2.zip)

**Comment by veeenu** [comment]
Can you try the [nightly release](https://github.com/veeenu/eldenring-practice-tool/releases/tag/nightly)? Just added a potential workaround (@etra0: I'm considering adding back the dummy HWND in the hopes it will solve the race condition).

**Comment by NevResTV** [comment]
With the new nightly release everything seems to work fine. The Tool opens normally and I can use the features I needed. Thank you very much and stay healthy^^

**Comment by stas1c** [comment]
Had the same issue. Tried nightly release and for the first launch it worked fine. After that every launch of the tool ends in game crash.

**Comment by veeenu** [comment]
That's great to know! I will publish a patch release sometime soon, make sure to upgrade to that whenever it comes out (you should get a notification from the tool itself).

**Comment by etra0** [comment]
hey, thanks for the heads up. FWIW I just received another report about this same problem for `Windows 11 22h2 22621.963`. I only found this https://stackoverflow.com/questions/71515127/d3d11createdeviceandswapchain-fails-with-e-accessdenied-when-using-same-hwnd which seems possible to have a data race with HWNDs, so the dummy one could be a good fix.

I also tried checking what Reshade does but it's... a bit more complicated to what I had time to check, lol.
